name: Windows Server 2019

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        arch: ["x86", "x64"]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodule: recursive
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
